site_name: Empire Chain
site_description: An orchestration framework for all your AI needs
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quickstart: getting-started/quickstart.md
  - User Guide:
    - Core Concepts: user-guide/core-concepts.md
    - Document Processing: user-guide/document-processing.md
    - LLM Integration: user-guide/llm-integration.md
    - Visualization: user-guide/visualization.md
  - API Reference:
    - LLMs: api-reference/llms.md
    - Vector Stores: api-reference/vector-stores.md
  - Tutorials:
    - Chat with PDF: tutorials/chat-with-pdf.md
    - Empire RAG: tutorials/empire-rag.md
  - Components:
    - Empire Agent: components/empire_agent.md
    - RAG: components/rag.md
    - Vector Stores: components/vector_stores.md
    - Chatbots: components/chatbots.md
    - PhiData Agents: components/phidata_agents.md
    - Tools: components/tools.md
    - Cool Stuff: components/cool_stuff.md
  - Contributing: contributing.md
  - License: license.md 